### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jzvi12** [StAndrewsRadio/starbot-forwarder#4]
Hey, this seems to be a very interesting tool I'd like to try from my Discord voice channel to my Icecast radio.

How to compile from Linux terminal? (I'm using Ubuntu 18.04 VPS)
I've downloaded Oracle Java SDK v11 but I'm not a Java guy so not sure how to compile those *.java files in src.

Thanks

**Comment by jzvi12** [comment]
I was  able to install Maven and built the project 
![image](https://user-images.githubusercontent.com/10729787/116831921-3e0af080-ab80-11eb-86c2-2fd77420c4f8.png)

I tried the following commands without success:
```
java -jar forwarder-0.1.0-SNAPSHOT.jar
```
```
no main manifest attribute, in forwarder-0.1.0-SNAPSHOT.jar
```
also:
```
java -jar forwarder-0.1.0-SNAPSHOT.jar com.standrewsradio.starbot.forwarder.Main
```

```
no main manifest attribute, in forwarder-0.1.0-SNAPSHOT.jar
```

**Comment by jzvi12** [comment]
I was able to build using Maven
![image](https://user-images.githubusercontent.com/10729787/116832677-03a35280-ab84-11eb-974f-247ec0b75322.png)

I tried:
```
$ java -jar forwarder-0.1.0-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" picocli.CommandLine$MissingParameterException: Missing required options [--token=<token>, --channel-id=<channelId>]
        at picocli.CommandLine$MissingParameterException.create(CommandLine.java:15726)
        at picocli.CommandLine$MissingParameterException.access$17000(CommandLine.java:15708)
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:11480)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11471)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11345)
        at picocli.CommandLine.parseArgs(CommandLine.java:1311)
        at com.standrewsradio.starbot.forwarder.Main.main(Main.java:19)
```
Also tried:
```
java -jar forwarder-0.1.0-SNAPSHOT-jar-with-dependencies.jar -t $TOKEN -c $CHANNEL_ID -r 41000 -l $ACTIVITY icecast://source:mypwd@icecastradio:8080/live
```
but getting:
```
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unmatched arguments from index 9: 'en', 'Radio', 'Yajad', 'icecast://source:natzratim517@150.136.173.228:8010/envivo'
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:11491)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11471)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11345)
        at picocli.CommandLine.parseArgs(CommandLine.java:1311)
        at com.standrewsradio.starbot.forwarder.Main.main(Main.java:19)
```

**Comment by kezz** [comment]
Hmm that's odd - do your arguments have spaces in them? If so, they probably need to be surrounded with quotes?

**Comment by jzvi12** [comment]
Thanks! One argument was not surrounded with quotes. It is now solved and working as expected. 👍
